<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="LibraryRoot.props" Condition="'$(LIBS_ROOT)'==''" />
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros">
    <CLPERFMARKER_ROOT>$(LIBS_ROOT)\CLPerfMarker</CLPERFMARKER_ROOT>
  </PropertyGroup>
  <PropertyGroup />
  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalIncludeDirectories>$(CLPERFMARKER_ROOT)\include\; %(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
	</ItemDefinitionGroup>
	<ItemDefinitionGroup Condition=" '$(Platform)'=='win32' ">
		<Link>
			  <AdditionalLibraryDirectories>$(CLPERFMARKER_ROOT)\lib\x86\; %(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
			  <AdditionalDependencies>CLPerfMarker.lib; %(AdditionalDependencies)</AdditionalDependencies>
		</Link>
	</ItemDefinitionGroup>
	<ItemDefinitionGroup Condition=" '$(Platform)'=='x64' ">
		<Link>
			  <AdditionalLibraryDirectories>$(CLPERFMARKER_ROOT)\lib\x64\; %(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
			  <AdditionalDependencies>CLPerfMarker-x64.lib; %(AdditionalDependencies)</AdditionalDependencies>
		</Link>
	</ItemDefinitionGroup>

  <ItemGroup>
    <BuildMacro Include="CLPERFMARKER_ROOT">
      <Value>$(CLPERFMARKER_ROOT)</Value>
    </BuildMacro>
  </ItemGroup>
</Project>