<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="LibraryRoot.props" Condition="'$(LIBS_ROOT)'==''" />
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros">
    <DIRECTX_ROOT>c:\Program Files (x86)\Microsoft DirectX SDK (June 2010)</DIRECTX_ROOT>
  </PropertyGroup>
  <PropertyGroup />
  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalIncludeDirectories>$(DIRECTX_ROOT)\Include\; %(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
	</ItemDefinitionGroup>
	<ItemDefinitionGroup Condition=" '$(Platform)'=='win32' ">
		<Link>
			  <AdditionalLibraryDirectories>$(DIRECTX_ROOT)\lib\x86\; %(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
		</Link>
	</ItemDefinitionGroup>
	<ItemDefinitionGroup Condition=" '$(Platform)'=='x64' ">
		<Link>
			  <AdditionalLibraryDirectories>$(DIRECTX_ROOT)\lib\x64\; %(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
		</Link>
	</ItemDefinitionGroup>

  <ItemGroup>
    <BuildMacro Include="DIRECTX_ROOT">
      <Value>$(DIRECTX_ROOT)</Value>
    </BuildMacro>
  </ItemGroup>
</Project>