<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<Import Project="LibraryRoot.props" Condition="'$(LIBS_ROOT)'==''" />
	<ImportGroup Label="PropertySheets" />
	<PropertyGroup Label="UserMacros">
		<GLEW_ROOT>$(LIBS_ROOT)\glew-1.10.0\</GLEW_ROOT>
	</PropertyGroup>
	
	<ItemDefinitionGroup>
		<ClCompile>
			<AdditionalIncludeDirectories>$(GLEW_ROOT)\include\; %(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
		    <PreprocessorDefinitions>GLEW_STATIC;%(PreprocessorDefinitions)</PreprocessorDefinitions>
		</ClCompile>
	</ItemDefinitionGroup>
	
	<ItemDefinitionGroup>		
		<Link>
			  <AdditionalLibraryDirectories>$(GLEW_ROOT)\lib\; %(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
		</Link>
	</ItemDefinitionGroup>

	<ItemDefinitionGroup Condition=" '$(Platform)'=='win32' And '$(Configuration)'=='Release'">
		<Link>
			<AdditionalLibraryDirectories>$(GLEW_ROOT)\lib\Release\Win32; %(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
			<AdditionalDependencies>glew32s.lib; %(AdditionalDependencies)</AdditionalDependencies>
		</Link>
	</ItemDefinitionGroup>
	<ItemDefinitionGroup Condition=" '$(Platform)'=='win32' And '$(Configuration)'=='Debug'">
		<Link>
			<AdditionalLibraryDirectories>$(GLEW_ROOT)\lib\Debug\Win32; %(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
			<AdditionalDependencies>glew32sd.lib; %(AdditionalDependencies)</AdditionalDependencies>
		</Link>
	</ItemDefinitionGroup>
	
	<ItemDefinitionGroup Condition=" '$(Platform)'=='x64' And '$(Configuration)'=='Release'">
		<Link>
			<AdditionalLibraryDirectories>$(GLEW_ROOT)\lib\Release\x64; %(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
			<AdditionalDependencies>glew32s.lib; %(AdditionalDependencies)</AdditionalDependencies>
		</Link>
	</ItemDefinitionGroup>

	<ItemDefinitionGroup Condition=" '$(Platform)'=='x64' And '$(Configuration)'=='Debug'">
		<Link>
			<AdditionalLibraryDirectories>$(GLEW_ROOT)\lib\Debug\x64; %(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
			<AdditionalDependencies>glew32sd.lib; %(AdditionalDependencies)</AdditionalDependencies>
		</Link>
	</ItemDefinitionGroup>

	<ItemGroup>
		<BuildMacro Include="GLEW_ROOT">
			<Value>$(GLEW_ROOT)</Value>
		</BuildMacro>
	</ItemGroup>
</Project>