<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="LibraryRoot.props" Condition="'$(LIBS_ROOT)'==''" />
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros">
    <JPG_ROOT>$(LIBS_ROOT)\jpeg-6b</JPG_ROOT>
  </PropertyGroup>
  <PropertyGroup />
  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalIncludeDirectories>$(JPG_ROOT); %(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
	</ItemDefinitionGroup>
	<ItemDefinitionGroup Condition=" '$(Configuration)'=='Release' ">
		<Link>
			<AdditionalDependencies>jpeg.lib; %(AdditionalDependencies)</AdditionalDependencies>
		</Link>
	</ItemDefinitionGroup>
	<ItemDefinitionGroup Condition=" '$(Configuration)'=='Debug' ">
		<Link>
			<AdditionalDependencies>jpegd.lib; %(AdditionalDependencies)</AdditionalDependencies>
		</Link>
	</ItemDefinitionGroup>
	<ItemDefinitionGroup Condition=" '$(Platform)'=='win32' ">
		<Link>
			  <AdditionalLibraryDirectories>$(JPG_ROOT)\lib; %(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
		</Link>
	</ItemDefinitionGroup>
	<ItemDefinitionGroup Condition=" '$(Platform)'=='x64' ">
		<Link>
			  <AdditionalLibraryDirectories>$(JPG_ROOT)\lib\x64; %(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
		</Link>
	</ItemDefinitionGroup>

  <ItemGroup>
    <BuildMacro Include="JPG_ROOT">
      <Value>$(JPG_ROOT)</Value>
    </BuildMacro>
  </ItemGroup>
</Project>