<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<Import Project="LibraryRoot.props" Condition="'$(LIBS_ROOT)'==''" />
	<ImportGroup Label="PropertySheets" />
	<PropertyGroup Label="UserMacros">
		<BULLET_ROOT>$(LIBS_ROOT)\bullet-2.81-rev2613\</BULLET_ROOT>
	</PropertyGroup>
	
	<ItemDefinitionGroup>
		<ClCompile>
			<AdditionalIncludeDirectories>$(BULLET_ROOT)\src\; %(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
		</ClCompile>
	</ItemDefinitionGroup>
	
	<ItemDefinitionGroup>		
		<Link>
			  <AdditionalLibraryDirectories>$(BULLET_ROOT)\lib\; %(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
		</Link>
	</ItemDefinitionGroup>

	<ItemDefinitionGroup Condition=" '$(Platform)'=='win32' And '$(Configuration)'=='Release'">
		<Link>
			<AdditionalDependencies>BulletDynamics_vs2010.lib; BulletCollision_vs2010.lib; LinearMath_vs2010.lib; %(AdditionalDependencies)</AdditionalDependencies>
		</Link>
	</ItemDefinitionGroup>
	<ItemDefinitionGroup Condition=" '$(Platform)'=='win32' And '$(Configuration)'=='Debug'">
		<Link>
			<AdditionalDependencies>BulletDynamics_vs2010_debug.lib; BulletCollision_vs2010_debug.lib; LinearMath_vs2010_debug.lib;%(AdditionalDependencies)</AdditionalDependencies>
		</Link>
	</ItemDefinitionGroup>
	
	<ItemDefinitionGroup Condition=" '$(Platform)'=='x64' And '$(Configuration)'=='Release'">
		<Link>
			<AdditionalDependencies>BulletDynamics_vs2010_x64_release.lib; BulletCollision_vs2010_x64_release.lib;  LinearMath_vs2010_x64_release.lib;%(AdditionalDependencies)</AdditionalDependencies>
		</Link>
	</ItemDefinitionGroup>

	<ItemDefinitionGroup Condition=" '$(Platform)'=='x64' And '$(Configuration)'=='Debug'">
		<Link>
			<AdditionalDependencies>BulletDynamics_vs2010_x64_debug.lib;BulletCollision_vs2010_x64_debug.lib;  LinearMath_vs2010_x64_debug.lib;%(AdditionalDependencies)</AdditionalDependencies>
		</Link>
	</ItemDefinitionGroup>

	<ItemGroup>
		<BuildMacro Include="BULLET_ROOT">
			<Value>$(BULLET_ROOT)</Value>
		</BuildMacro>
	</ItemGroup>
</Project>