<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<Import Project="LibraryRoot.props" Condition="'$(LIBS_ROOT)'==''" />
	<ImportGroup Label="PropertySheets" />
	<PropertyGroup Label="UserMacros">
		<OVR_ROOT>$(LIBS_ROOT)\OculusSDK_5_0_1\LibOVR</OVR_ROOT>
	</PropertyGroup>
	
	<ItemDefinitionGroup>
		<ClCompile>
			<AdditionalIncludeDirectories>$(OVR_ROOT)\include\; %(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
		</ClCompile>
	</ItemDefinitionGroup>
	
	<ItemDefinitionGroup Condition=" '$(Platform)'=='win32' And '$(Configuration)'=='Release'">
		<Link>
			<AdditionalLibraryDirectories>$(OVR_ROOT)\lib\windows\Win32\Release\VS2013; %(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
			<AdditionalDependencies>libovr.lib; %(AdditionalDependencies)</AdditionalDependencies>
		</Link>
	</ItemDefinitionGroup>
	
	<ItemDefinitionGroup Condition=" '$(Platform)'=='win32' And '$(Configuration)'=='Debug'">
		<Link>
			<AdditionalLibraryDirectories>$(OVR_ROOT)\lib\windows\Win32\Debug\VS2013; %(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
			<AdditionalDependencies>libovr.lib; %(AdditionalDependencies)</AdditionalDependencies>
		</Link>
	</ItemDefinitionGroup>
	
	<ItemDefinitionGroup Condition=" '$(Platform)'=='x64' And '$(Configuration)'=='Release'">
		<Link>
			<AdditionalLibraryDirectories>$(OVR_ROOT)\lib\windows\x64\Release\VS2013; %(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
			<AdditionalDependencies>libovr.lib; %(AdditionalDependencies)</AdditionalDependencies>
		</Link>
	</ItemDefinitionGroup>

	<ItemDefinitionGroup Condition=" '$(Platform)'=='x64' And '$(Configuration)'=='Debug'">
		<Link>
			<AdditionalLibraryDirectories>$(OVR_ROOT)\lib\windows\x64\Debug\VS2013; %(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
			<AdditionalDependencies>libovr.lib; %(AdditionalDependencies)</AdditionalDependencies>
		</Link>
	</ItemDefinitionGroup>

	<ItemGroup>
		<BuildMacro Include="OVR_ROOT">
			<Value>$(OVR_ROOT)</Value>
		</BuildMacro>
	</ItemGroup>
</Project>