<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<Import Project="LibraryRoot.props" Condition="'$(LIBS_ROOT)'==''" />
	<ImportGroup Label="PropertySheets" />
	<PropertyGroup Label="UserMacros">
		<PNG_ROOT>$(LIBS_ROOT)\lpng1619\</PNG_ROOT>
	</PropertyGroup>
	
	<ItemDefinitionGroup>
		<ClCompile>
			<AdditionalIncludeDirectories>$(PNG_ROOT); %(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
		</ClCompile>
	</ItemDefinitionGroup>

	<ItemDefinitionGroup>
		<Link>
			<AdditionalDependencies>libpng16.lib; %(AdditionalDependencies)</AdditionalDependencies>
		</Link>
	</ItemDefinitionGroup>

	
	<ItemDefinitionGroup Condition=" '$(Platform)'=='win32' And '$(Configuration)'=='Release'">
		<Link>
			<AdditionalLibraryDirectories>$(PNG_ROOT)\projects\vstudio\Release Library\; %(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
		</Link>
	</ItemDefinitionGroup>
	<ItemDefinitionGroup Condition=" '$(Platform)'=='win32' And '$(Configuration)'=='Debug'">
		<Link>
			<AdditionalLibraryDirectories>$(PNG_ROOT)\projects\vstudio\Debug Library\; %(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
		</Link>
	</ItemDefinitionGroup>
	
	<ItemDefinitionGroup Condition=" '$(Platform)'=='x64' And '$(Configuration)'=='Release'">
		<Link>
			<AdditionalLibraryDirectories>$(PNG_ROOT)\projects\vstudio\x64\Release Library\; %(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
		</Link>
	</ItemDefinitionGroup>

	<ItemDefinitionGroup Condition=" '$(Platform)'=='x64' And '$(Configuration)'=='Debug'">
		<Link>
			<AdditionalLibraryDirectories>$(PNG_ROOT)\projects\vstudio\x64\Debug Library\; %(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
		</Link>
	</ItemDefinitionGroup>

	<ItemGroup>
		<BuildMacro Include="PNG_ROOT">
			<Value>$(PNG_ROOT)</Value>
		</BuildMacro>
	</ItemGroup>
</Project>