<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="LibraryRoot.props" Condition="'$(LIBS_ROOT)'==''" />
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros">
    <NVAPI_ROOT>$(LIBS_ROOT)\NVAPI_2012_09\</NVAPI_ROOT>
  </PropertyGroup>
  <PropertyGroup />
  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalIncludeDirectories>$(NVAPI_ROOT); %(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
	</ItemDefinitionGroup>
	<ItemDefinitionGroup Condition=" '$(Platform)'=='win32' ">
		<Link>
			  <AdditionalLibraryDirectories>$(NVAPI_ROOT)\x86\; %(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
		</Link>
	</ItemDefinitionGroup>
	<ItemDefinitionGroup Condition=" '$(Platform)'=='x64' ">
		<Link>
			  <AdditionalLibraryDirectories>$(NVAPI_ROOT)\amd64\; %(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
		</Link>
	</ItemDefinitionGroup>

  <ItemGroup>
    <BuildMacro Include="NVAPI_ROOT">
      <Value>$(NVAPI_ROOT)</Value>
    </BuildMacro>
  </ItemGroup>
</Project>