<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="LibraryRoot.props" Condition="'$(LIBS_ROOT)'==''" />
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros">
    <NVTT_ROOT>$(LIBS_ROOT)\NVTX\c\</NVTT_ROOT>
  </PropertyGroup>
  <PropertyGroup />
  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalIncludeDirectories>$(NVTT_ROOT)\include; %(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
	</ItemDefinitionGroup>
	
  <ItemGroup>
    <BuildMacro Include="NVTT_ROOT">
      <Value>$(NVTT_ROOT)</Value>
    </BuildMacro>
  </ItemGroup>
</Project>