<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<Import Project="LibraryRoot.props" Condition="'$(LIBS_ROOT)'==''" />
	<ImportGroup Label="PropertySheets" />
	<PropertyGroup Label="UserMacros">
		<OPENVR_ROOT>$(LIBS_ROOT)\openvr\</OPENVR_ROOT>
	</PropertyGroup>
	
	<ItemDefinitionGroup>
		<ClCompile>
			<AdditionalIncludeDirectories>$(OPENVR_ROOT)\headers; %(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
		</ClCompile>
	</ItemDefinitionGroup>
	
	<ItemDefinitionGroup Condition=" '$(Platform)'=='win32'">
		<Link>
			<AdditionalLibraryDirectories>$(OPENVR_ROOT)\lib\win32\; %(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
			<AdditionalDependencies>openvr_api.lib; %(AdditionalDependencies)</AdditionalDependencies>
		</Link>
	</ItemDefinitionGroup>
	
	<ItemDefinitionGroup Condition=" '$(Platform)'=='x64'">
		<Link>
			<AdditionalLibraryDirectories>$(OPENVR_ROOT)\lib\win64\; %(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
			<AdditionalDependencies>openvr_api.lib; %(AdditionalDependencies)</AdditionalDependencies>
		</Link>
	</ItemDefinitionGroup>

	<ItemGroup>
		<BuildMacro Include="OPENVR_ROOT">
			<Value>$(OPENVR_ROOT)</Value>
		</BuildMacro>
	</ItemGroup>
</Project>