<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<Import Project="LibraryRoot.props" Condition="'$(LIBS_ROOT)'==''" />
	<ImportGroup Label="PropertySheets" />
	<PropertyGroup Label="UserMacros">
		<SHADERC_ROOT>$(LIBS_ROOT)\shaderc</SHADERC_ROOT>
	</PropertyGroup>
	<PropertyGroup />

	<ItemDefinitionGroup>
		<ClCompile>
		  <AdditionalIncludeDirectories>$(SHADERC_ROOT)\libshaderc\include; %(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
		</ClCompile>
	</ItemDefinitionGroup>
	<ItemDefinitionGroup Condition=" '$(Configuration)'=='Release' ">
		<Link>
			<AdditionalLibraryDirectories>$(SHADERC_ROOT)\cmake_build\libshaderc\Release; $(SHADERC_ROOT)\libshaderc_util\Release; %(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
			<AdditionalDependencies>shaderc_combined.lib; %(AdditionalDependencies)</AdditionalDependencies>
		</Link>
	</ItemDefinitionGroup>
	<ItemDefinitionGroup Condition=" '$(Configuration)'=='Debug' ">
		<Link>
			<AdditionalLibraryDirectories>$(SHADERC_ROOT)\cmake_build\libshaderc\Debug; $(SHADERC_ROOT)\libshaderc_util\Debug; %(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
			<AdditionalDependencies>shaderc_combinedd.lib; %(AdditionalDependencies)</AdditionalDependencies>
		</Link>
	</ItemDefinitionGroup>
	<ItemGroup>
		<BuildMacro Include="SHADERC_ROOT">
			<Value>$(SHADERC_ROOT)</Value>
		</BuildMacro>
	</ItemGroup>
</Project>