//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DXSHELLLIB.RC
//
#define IDI_APPICON 99
#define IDI_APP 100
#define IDD_DRIVERSELECTOR 101
#define IDD_SCREENMODE 102
#define IDI_AUDIO 103
#define IDI_DEVICE 104
#define IDI_DIRECTX 105
#define IDI_SCREENMODE 106
#define IDR_ACCELERATOR 113
#define IDD_WORLDVIEW 114
#define IDC_DEVICE 1000
#define IDC_DESCRIPTION 1001
#define IDC_FRAME2 1002
#define IDC_MODELIST 1003
#define IDC_FULLSCREEN 1005
#define IDC_TREE1 1009
#define IDC_FSAASLIDER 1010
#define IDC_FSAASLIDER1 1010
#define IDA_TOGGLEFULLSCREEN 40001
#define IDC_FRAME1 -1

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE 132
#define _APS_NEXT_COMMAND_VALUE 40002
#define _APS_NEXT_CONTROL_VALUE 1012
#define _APS_NEXT_SYMED_VALUE 101
#endif
#endif
